"""intial revision

Revision ID: 0ef0dc05fbb5
Revises: 90a1814f296b
Create Date: 2025-09-14 18:19:23.680484

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "0ef0dc05fbb5"
down_revision: Union[str, Sequence[str], None] = "90a1814f296b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "queued",
        "processing",
        "done",
        "published",
        "failed",
        "cancelled",
        name="videojobstatus",
    ).create(op.get_bind())
    sa.Enum("youtube", "twitch", "instagram", name="socialplatform").create(
        op.get_bind()
    )
    sa.Enum("user", "admin", name="userrole").create(op.get_bind())
    op.create_table(
        "refresh_tokens",
        sa.Column(
            "refresh_token_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("hashed_token", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("refresh_token_id"),
        sa.UniqueConstraint("hashed_token"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("google_id", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "user", "admin", name="userrole", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "video_formats",
        sa.Column(
            "video_format_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.CheckConstraint("price >= 0", name="check_price_non_negative"),
        sa.PrimaryKeyConstraint("video_format_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "social_accounts",
        sa.Column(
            "social_account_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "platform",
            postgresql.ENUM(
                "youtube",
                "twitch",
                "instagram",
                name="socialplatform",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("credentials", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("social_account_id"),
    )
    op.create_table(
        "video_jobs",
        sa.Column(
            "video_job_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("format_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "queued",
                "processing",
                "done",
                "published",
                "failed",
                "cancelled",
                name="videojobstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("video_url", sa.String(), nullable=True),
        sa.Column("publish_automatically", sa.Boolean(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["format_id"],
            ["video_formats.video_format_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("video_job_id"),
    )
    op.create_table(
        "video_job_social_account",
        sa.Column("video_job_id", sa.Integer(), nullable=False),
        sa.Column("social_account_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["social_account_id"],
            ["social_accounts.social_account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_job_id"],
            ["video_jobs.video_job_id"],
        ),
        sa.PrimaryKeyConstraint("video_job_id", "social_account_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_job_social_account")
    op.drop_table("video_jobs")
    op.drop_table("social_accounts")
    op.drop_table("video_formats")
    op.drop_table("users")
    op.drop_table("refresh_tokens")
    sa.Enum("user", "admin", name="userrole").drop(op.get_bind())
    sa.Enum("youtube", "twitch", "instagram", name="socialplatform").drop(
        op.get_bind()
    )
    sa.Enum(
        "queued",
        "processing",
        "done",
        "published",
        "failed",
        "cancelled",
        name="videojobstatus",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
