"""empty message

Revision ID: 436f2849440e
Revises: 85bb721e84eb
Create Date: 2025-10-15 17:53:54.001464

"""

from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "436f2849440e"
down_revision: Union[str, Sequence[str], None] = "85bb721e84eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "video_job_social_account_social_account_id_fkey",
        "video_job_social_account",
        type_="foreignkey",
    )
    op.alter_column(
        "social_accounts",
        "social_account_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text(
            "nextval('social_accounts_social_account_id_seq'::regclass)"
        ),
    )
    op.alter_column(
        "video_job_social_account",
        "social_account_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.create_foreign_key(
        "video_job_social_account_social_account_id_fkey",
        "video_job_social_account",
        "social_accounts",
        ["social_account_id"],
        ["social_account_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "video_job_social_account",
        "social_account_id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "social_accounts",
        "social_account_id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text(
            "nextval('social_accounts_social_account_id_seq'::regclass)"
        ),
    )
    # ### end Alembic commands ###
