"""empty message

Revision ID: 85bb721e84eb
Revises: 317ab8febdca
Create Date: 2025-10-15 17:39:23.537683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85bb721e84eb'
down_revision: Union[str, Sequence[str], None] = '317ab8febdca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    #  we need to first drop the foreign key constraint on video_job_social_account
    #  that references video_jobs.video_job_id, then alter the column types,
    #  and finally re-add the foreign key constraint.
    op.drop_constraint('video_job_social_account_video_job_id_fkey', 'video_job_social_account', type_='foreignkey')
    op.alter_column('video_jobs', 'video_job_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('video_job_social_account', 'video_job_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(
        'video_job_social_account_video_job_id_fkey', 
        'video_job_social_account', 
        'video_jobs', 
        ['video_job_id'], 
        ['video_job_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_jobs', 'video_job_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('video_job_social_account', 'video_job_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
