"""initial version

Revision ID: 90a1814f296b
Revises:
Create Date: 2025-09-14 17:54:58.292705

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "90a1814f296b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
