"""empty message

Revision ID: ad18d2ffe2b7
Revises: 436f2849440e
Create Date: 2025-10-15 20:16:43.524613

"""

from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad18d2ffe2b7"
down_revision: Union[str, Sequence[str], None] = "436f2849440e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("video_jobs", sa.Column("creator_id", sa.String(), nullable=False))
    op.drop_constraint(op.f("fk_video_jobs_user_id"), "video_jobs", type_="foreignkey")
    op.create_foreign_key(None, "video_jobs", "users", ["creator_id"], ["user_id"])
    op.drop_column("video_jobs", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "video_jobs",
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "video_jobs", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_video_jobs_user_id"), "video_jobs", "users", ["user_id"], ["user_id"]
    )
    op.drop_column("video_jobs", "creator_id")
    # ### end Alembic commands ###
