"""empty message

Revision ID: b25bf0d9aeaf
Revises: f0851e4680a5
Create Date: 2025-10-25 18:27:12.744527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25bf0d9aeaf'
down_revision: Union[str, Sequence[str], None] = 'f0851e4680a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('owner_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('fk_social_accounts_user_id'), 'social_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'social_accounts', 'users', ['owner_id'], ['user_id'])
    op.drop_column('social_accounts', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'social_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_social_accounts_user_id'), 'social_accounts', 'users', ['user_id'], ['user_id'])
    op.drop_column('social_accounts', 'owner_id')
    # ### end Alembic commands ###
