"""add_payment_provider_id_to_balance_transactions

Revision ID: b5580561ff1c
Revises: e922ed3151d2
Create Date: 2026-04-02 14:34:33.277689

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5580561ff1c"
down_revision: Union[str, Sequence[str], None] = "e922ed3151d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "balance_transactions",
        sa.Column("payment_provider_id", sa.String(), nullable=True),
    )
    op.create_index(
        op.f("ix_balance_transactions_payment_provider_id"),
        "balance_transactions",
        ["payment_provider_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_balance_transactions_payment_provider_id"),
        table_name="balance_transactions",
    )
    op.drop_column("balance_transactions", "payment_provider_id")
    # ### end Alembic commands ###
