"""empty message

Revision ID: c700103fdc80
Revises: b25bf0d9aeaf
Create Date: 2025-11-08 22:18:09.511846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'c700103fdc80'
down_revision: Union[str, Sequence[str], None] = 'b25bf0d9aeaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('platform_account_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_social_accounts_platform_account_id'), 'social_accounts', ['platform_account_id'], unique=False)
    op.sync_enum_values(
        enum_schema='public',
        enum_name='socialplatform',
        new_values=['youtube', 'tiktok', 'instagram'],
        affected_columns=[TableReference(table_schema='public', table_name='social_accounts', column_name='platform')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='socialplatform',
        new_values=['youtube', 'twitch', 'instagram'],
        affected_columns=[TableReference(table_schema='public', table_name='social_accounts', column_name='platform')],
        enum_values_to_rename=[],
    )
    op.drop_index(op.f('ix_social_accounts_platform_account_id'), table_name='social_accounts')
    op.drop_column('social_accounts', 'platform_account_id')
    # ### end Alembic commands ###
