"""add_reserved_balance_and_balance_transactions

Revision ID: e922ed3151d2
Revises: c812d05958ce
Create Date: 2026-03-31 20:29:36.111106

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e922ed3151d2"
down_revision: Union[str, Sequence[str], None] = "c812d05958ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "reservation",
        "confirmation",
        "release",
        "top_up",
        name="balancetransactiontype",
    ).create(op.get_bind())
    op.create_table(
        "balance_transactions",
        sa.Column(
            "balance_transaction_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=True),
        sa.Column(
            "type",
            postgresql.ENUM(
                "reservation",
                "confirmation",
                "release",
                "top_up",
                name="balancetransactiontype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["video_jobs.video_job_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("balance_transaction_id"),
    )
    op.create_index(
        op.f("ix_balance_transactions_job_id"),
        "balance_transactions",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_balance_transactions_user_id"),
        "balance_transactions",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "users",
        sa.Column(
            "reserved_balance", sa.Float(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "reserved_balance")
    op.drop_index(
        op.f("ix_balance_transactions_user_id"),
        table_name="balance_transactions",
    )
    op.drop_index(
        op.f("ix_balance_transactions_job_id"),
        table_name="balance_transactions",
    )
    op.drop_table("balance_transactions")
    sa.Enum(
        "reservation",
        "confirmation",
        "release",
        "top_up",
        name="balancetransactiontype",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
