"""refresh_tokens model updated

Revision ID: e9fb8a49f484
Revises: 0ef0dc05fbb5
Create Date: 2025-09-16 18:57:41.705456

"""

from typing import Sequence, Union

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "e9fb8a49f484"
down_revision: Union[str, Sequence[str], None] = "0ef0dc05fbb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "refresh_tokens", "users", ["user_id"], ["user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "refresh_tokens", type_="foreignkey")
    # ### end Alembic commands ###
