"""empty message

Revision ID: f0851e4680a5
Revises: ad18d2ffe2b7
Create Date: 2025-10-25 18:24:34.345523

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "f0851e4680a5"
down_revision: Union[str, Sequence[str], None] = "ad18d2ffe2b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "social_accounts",
        sa.Column("encrypted_credentials", sa.LargeBinary(), nullable=False),
    )
    op.add_column(
        "social_accounts",
        sa.Column("wrapped_dek", sa.LargeBinary(), nullable=False),
    )
    op.add_column(
        "social_accounts", sa.Column("kek_id", sa.Integer(), nullable=False)
    )
    op.drop_column("social_accounts", "credentials")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "social_accounts",
        sa.Column(
            "credentials",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("social_accounts", "kek_id")
    op.drop_column("social_accounts", "wrapped_dek")
    op.drop_column("social_accounts", "encrypted_credentials")
    # ### end Alembic commands ###
